### ISSUE TITLE
Question. How To Add Cores?

### ISSUE THREAD

**Issue by Shibedev12** [mac2612/retroleap#41]
So If I wanted to play pokemon blue, how would i go about running gb games on retroleap?

**Comment by andymcca** [comment]
You have several options depending on your Leapfrog device.

In the stock releases of retroleap for LF2000 (Leapfrog Leappad 2 and Leapster GS Explorer), the gpsp core is included in Retroarch for playing GBA games.  For LF1000 (Leappad 1 and Leapster Explorer), ohboy is included for running Gameboy/Gameboy Color games.

If you check out my repos you'll find additional cores, an overclocked version of retroleap for Leapster GS Explorer and an add-on pack for LF1000 retroleap (specifically the Leapster Explorer) which adds Retroarch/gpsp.

You also have the option of building retroleap yourself from the github sources, during which you can specify which cores/emulators you'd like to build (instructions in the retroleap readme).

**Comment by Shibedev12** [comment]
thanks! i forgor that that was a thing. now i can play faceball 2k!
