### ISSUE TITLE
"upgrade" process

### ISSUE THREAD

**Issue by claud9999** [mac2612/retroleap#54]
So I'm *assuming* that the process to upgrade from 2.0.4 to 2.0.5 is to use the same sshflash procedure, but I'd hate to lose my /roms folder (I have some state saves.) Can the README.md be updated to add upgrade instructions?

**Comment by Th3KillinJok3** [comment]
As a person who flashes firmwares daily back and forth testing what I am comfortable with:
1. Make a ROM/Save backup through WinSCP
2. Make sure to say "no" at the point when sshflash asks for ROM folder flash :) 
I ran through several varieties of firmware now, and nothing's gone bad with either my ROMs or Saves :)

**Comment by claud9999** [comment]
> As a person who flashes firmwares daily back and forth testing what I am comfortable with:
> 
>     1. Make a ROM/Save backup through WinSCP
> 
>     2. Make sure to say "no" at the point when sshflash asks for ROM folder flash :)
>        I ran through several varieties of firmware now, and nothing's gone bad with either my ROMs or Saves :)

Thanks!
